### ISSUE TITLE
declare custom commands in user files

### ISSUE THREAD

**Issue by adamsky** [adamsky/outcome#32]
Custom commands are aliases that use either lua or dynlib functionality. Declaring such custom command would have to include setting up free and optional arguments and how they are passed to the actual built-in cmd (`lua_call` or `lib_call`)

**Comment by adamsky** [comment]
This should probably just be called `alias`ing

**Comment by adamsky** [comment]
```yaml
# module declaration block
aliases:
- name: dostuff
  path: "lua/test.lua"
  func: process_grid
  args_pos:
  - name: "var1"
    type: int
  return:
    type: int
```

This example alias would change
`- process_grid int/test1 int/test2 | int/main`
into
`- lua_call process_grid --args="int/test1,int/test2" | int/main`

It would complain if the var type for args or return were wrong.

Additionally it would add the proper script path to the lua script object at the entity to which the component is attached.
